---
title: "EF"
format: html
editor: visual
---

## Examen Final

**Nombre**: Jeffrey Monja Castro

```{r}
library(readr)
library(dplyr)
```

```{r}
r <- function(x){
  return(round(x, digits = 2))
}
```

```{r}
DF <- read_csv('DFB.csv')
DF
```

### Pregunta 1

```{r}
p1 <- 6*5*4
p2 <- 6*5*4*3*2

N <- 6
M <- 3
n <- 3

r(dhyper(3, N, N-M, N))
```

### Pregunta 2

Por dato 0.61

### Pregunta 3
```{r}
DF %>% filter(Tipo == 'B') -> DF2
```

```{r}
p <- mean(DF2$Nota)
p/100 -> p
p

#valor esperado
100*p

#desviación
r(sqrt(100*p*(1-p)))
```

### Pregunta 4
```{r}
DF %>% filter(Tipo == 'A' & Nota >= 55) -> DF3
DF %>% filter(Tipo == 'A') -> DF4

# Jalar
p1 <- nrow(DF3)/nrow(DF)

p2 <- nrow(DF4)/nrow(DF)

p1 - p2

#Mención destacada
DF %>% filter(Tipo == 'A' & Nota > 75) -> DF5

r(nrow(DF5)/nrow(DF4))
```

### Pregunta 5

```{r}
# Exactamente 75 pts
DF %>% filter(Nota == 75) -> DF6
prob_75 <- nrow(DF6)/nrow(DF)
r(prob_75)

# Bayes
DF %>% filter(Nota == 75 & Tipo == 'A') -> DF7
p_A_itersec_75 <- nrow(DF7)/nrow(DF)

p_A_itersec_75/prob_75

```

### Pregunta 6

```{r}
summary(DF$Nota)
```
```{r}
hist(DF$Nota, breaks=30)
mean(DF$Nota)
```

```{r}
DF %>% filter(Nota>= 55) %>% select(Nota) %>% count()/nrow(DF)
```


